### ISSUE TITLE
Errors while loading plugin

### ISSUE THREAD

**Issue by mayersj1** [amix/vim-zenroom2#5]
Error detected while processing /Users/smayer/.vim/bundle/vim-zenroom2/plugin/zenroom2.vim:
line   65:
E128: Function name must start with a capital or "s:": g:zenroom_goyo_before()
line   67:
E133: :return not inside a function
line   74:
E193: :endfunction not inside a function
line   76:
E128: Function name must start with a capital or "s:": g:zenroom_goyo_after()
line   78:
E133: :return not inside a function
line   88:
E193: :endfunction not inside a function
line   90:
E700: Unknown function: g:zenroom_goyo_before
E700: Unknown function: g:zenroom_goyo_after

Changing the plugin to use 's' rather than 'g' in these two function definitions and the two function references solves the issue. i.e. g:zenroom_goyo_before() becomes s:zenroom_goyo_before(), g:zenroom_goyo_after() becomes s:zenroom_goyo_after() and the two references get changed to the new names.

Plugin loaded fine after these changes.

Tested using latest vim on both OSX and Linux.

**Comment by ee0pdt** [comment]
Why is this closed? I'm still seeing this issue

**Comment by amix** [comment]
@ee0pdt because it's an issue with the vim installation and not the vimrc setup...

**Comment by ee0pdt** [comment]
that's interesting as it only started happening when I upgraded to macOS Sierra - I wonder if Apple have changed the version of vim they ship
